name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo "Installing..."
    - run: echo "Testing..."
    - run: echo "Deploying..."
